# .github/workflows/main.yml

name: CI/CD Docker Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build-and-push"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4 # Use the latest version

      # Optional: Add steps here to run tests (e.g., using pytest)
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'
      # - name: Install dependencies for testing
      #   run: pip install pytest # Add other test dependencies
      # - name: Run tests
      #   run: pytest # Assuming you have tests in a 'tests' folder or similar

      # Set up Docker Buildx for more advanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Use token, not password

      # Build the Docker image and push it to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the current directory as context
          file: ./Dockerfile # Path to the Dockerfile
          push: true # Actually push the image
          # Tag the image with 'latest' and a unique Git SHA
          # Replace 'your-dockerhub-username' with your actual Docker Hub username
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest,${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:${{ github.sha }}
          # Enable build cache for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Logout from Docker Hub
        # Run this step only if the previous steps were successful
        if: always()
        run: docker logout
